/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example


fun nombre_fecha (){
    println("juan rodriguez")
    println("22/04/25")}

fun main() {
    println("hola kotlin")
    nombre_fecha()

}
